// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPNZGJBsuMkfBw3xUtvIqJvgWByP3ptBY',
    appId: '1:854932331237:web:bd61a8e64ef490554d920c',
    messagingSenderId: '854932331237',
    projectId: 'zamlista-6cdf1',
    authDomain: 'zamlista-6cdf1.firebaseapp.com',
    storageBucket: 'zamlista-6cdf1.appspot.com',
    measurementId: 'G-0PFXNQCX58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDOmzExI0pYrag2UyRImgw2Z0lswVKBqs',
    appId: '1:854932331237:android:62038f025ed3d0284d920c',
    messagingSenderId: '854932331237',
    projectId: 'zamlista-6cdf1',
    storageBucket: 'zamlista-6cdf1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzFrHblJQ3v5h9TzVt1fyRiTHOtlfFtkw',
    appId: '1:854932331237:ios:057ab3a704d771fb4d920c',
    messagingSenderId: '854932331237',
    projectId: 'zamlista-6cdf1',
    storageBucket: 'zamlista-6cdf1.appspot.com',
    iosBundleId: 'com.example.zamlista',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzFrHblJQ3v5h9TzVt1fyRiTHOtlfFtkw',
    appId: '1:854932331237:ios:fb39aa4cb0437b874d920c',
    messagingSenderId: '854932331237',
    projectId: 'zamlista-6cdf1',
    storageBucket: 'zamlista-6cdf1.appspot.com',
    iosBundleId: 'yes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPNZGJBsuMkfBw3xUtvIqJvgWByP3ptBY',
    appId: '1:854932331237:web:6be4e13dc19b8d1d4d920c',
    messagingSenderId: '854932331237',
    projectId: 'zamlista-6cdf1',
    authDomain: 'zamlista-6cdf1.firebaseapp.com',
    storageBucket: 'zamlista-6cdf1.appspot.com',
    measurementId: 'G-9NQBYB48M0',
  );
}
